before:
  hooks:
    - go mod tidy

builds:
  - main: main.go
    binary: githubTest2
    id: githubTest2

    env:
      - CGO_ENABLED=0

    goos: [windows,linux,darwin]
    goarch: [amd64,arm64]

    flags:
      - -trimpath

archives:
  - format: zip
    id: githubTest2
    builds: [githubTest2]
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ if eq .Os "darwin" }}macOS{{ else }}{{ .Os }}{{ end }}_{{ .Arch }}'

checksum:
  algorithm: sha256